# Copyright (c) Meta Platforms, Inc. and affiliates.

import numpy as np

VERTS_OPEN = [
    [78, 121],
    [121, 214],
    [214, 215],
    [215, 279],
    [279, 239],
    [239, 234],
    [234, 92],
    [92, 38],
    [38, 122],
    [122, 118],
    [118, 117],
    [117, 119],
    [119, 120],
    [120, 108],
    [108, 79],
    [79, 78],
]

verts_open_id = list(set([v for edge in VERTS_OPEN for v in edge]))

def make_mano_sequence_wt(verts_hand_l, verts_hand_r, faces_hand_l, faces_hand_r):

    verts_open_id = list(set([v for edge in VERTS_OPEN for v in edge]))

    # compute barycenters from right hand loops
    barycenter_r = np.mean(verts_hand_r[:, verts_open_id, :], axis=1)[:, np.newaxis, :]
    # add as new vert
    verts_hand_r_wt = np.concatenate([verts_hand_r, barycenter_r], 1)
    extra_vert_ID = verts_hand_r_wt.shape[1] - 1
    # add new faces
    extra_faces = np.array([edge + [extra_vert_ID] for edge in VERTS_OPEN])
    faces_hand_r_wt = np.concatenate([faces_hand_r, extra_faces])

    # compute barycenters from right hand loops
    barycenter_l = np.mean(verts_hand_l[:, verts_open_id, :], axis=1)[:, np.newaxis, :]
    # add as new vert
    verts_hand_l_wt = np.concatenate([verts_hand_l, barycenter_l], 1)
    extra_vert_ID = verts_hand_l_wt.shape[1] - 1
    # add new faces
    extra_faces = np.array([edge[::-1] + [extra_vert_ID] for edge in VERTS_OPEN])
    faces_hand_l_wt = np.concatenate([faces_hand_l, extra_faces])

    return verts_hand_l_wt, verts_hand_r_wt, faces_hand_l_wt, faces_hand_r_wt

OBJECT_LIST = [
    "cylinderlarge",
    "mug",
    "elephant",
    "hand",
    "cubelarge",
    "stanfordbunny",
    "airplane",
    "alarmclock",
    "banana",
    "body",
    "bowl",
    "cubesmall",
    "cup",
    "doorknob",
    "cubemedium",
    "eyeglasses",
    "flashlight",
    "flute",
    "gamecontroller",
    "hammer",
    "headphones",
    "knife",
    "lightbulb",
    "mouse",
    "phone",
    "piggybank",
    "pyramidlarge",
    "pyramidsmall",
    "pyramidmedium",
    "duck",
    "scissors",
    "spherelarge",
    "spheresmall",
    "stamp",
    "stapler",
    "table",
    "teapot",
    "toruslarge",
    "torussmall",
    "train",
    "watch",
    "cylindersmall",
    "waterbottle",
    "torusmedium",
    "cylindermedium",
    "spheremedium",
    "wristwatch",
    "wineglass",
    "camera",
    "binoculars",
    "fryingpan",
    "toothpaste",
    "apple",
    "toothbrush",
]

OBJECT_LIST_NEW = [
    "large cylinder",
    "mug",
    "elephant",
    "hand",
    "large cube",
    "stanfordbunny",
    "airplane",
    "alarmclock",
    "alarm clock",
    "banana",
    "body",
    "bowl",
    "small cube",
    "cup",
    "doorknob",
    "medium cube",
    "eyeglasses",
    "flashlight",
    "flute",
    "gamecontroller",
    "hammer",
    "headphones",
    "knife",
    "lightbulb",
    "mouse",
    "phone",
    "piggybank",
    "large pyramid",
    "small pyramid",
    "medium pyramid",
    "duck",
    "scissors",
    "large sphere",
    "small sphere",
    "stamp",
    "stapler",
    "table",
    "teapot",
    "large torus",
    "small torus",
    "train",
    "watch",
    "small cylinder",
    "waterbottle",
    "medium torus",
    "medium cylinder",
    "medium sphere",
    "wristwatch",
    "wineglass",
    "camera",
    "binoculars",
    "fryingpan",
    "toothpaste",
    "apple",
    "toothbrush",
]

GENDER_MAP = {
    "s1": "male",
    "s2": "male",
    "s3": "female",
    "s4": "female",
    "s5": "female",
    "s6": "female",
    "s7": "female",
    "s8": "male",
    "s9": "male",
    "s10": "male",
}

YCB_LIST = [
    "can",
    "box",
    "sugar box",
    "soup can",
    "bottle",
    "tuna can",
    "pudding box",
    "gelatin box",
    "meat can",
    "banana",
    "pitcher",
    "cleanser",
    "bowl",
    "mug",
    "drill",
    "block",
    "scissors",
    "marker",
    "clamp",
    "brick",
]

OBJ_TO_YCB = {
    "large can": "002_master_chef_can",
    "drill": "035_power_drill",
    "mug": "025_mug",
    "marker": "040_large_marker",
    "pitcher": "019_pitcher_base",
    "scissors": "037_scissors",
    "clamp": "052_extra_large_clamp",
    "block": "036_wood_block",
    "brick": "061_foam_brick",
    "bowl": "024_bowl",
    "cracker box": "003_cracker_box",
    "large box": "003_cracker_box",
    "cereal box": "003_cracker_box",
    "small can": "005_tomato_soup_can",
    "can": "005_tomato_soup_can",
    "sugar box": "004_sugar_box",
    "mustard bottle": "006_mustard_bottle",
    "tuna fish can": "007_tuna_fish_can",
    "pudding box": "008_pudding_box",
    "gelatin box": "009_gelatin_box",
    "potted meat can": "010_potted_meat_can",
    "banana": "011_banana",
    "bleach cleanser": "021_bleach_cleanser",
}

OBJ_TO_YCB_MESH = {
    "large can": "002_master_chef_can/master_chef_can.stl",
    "drill": "035_power_drill/textured.obj",
    "mug": "025_mug/mug.stl",
    "marker": "040_large_marker/textured.obj",
    "pitcher": "019_pitcher_base/textured.obj",
    "scissors": "037_scissors/textured.obj",
    "clamp": "052_extra_large_clamp/textured.obj",
    "block": "036_wood_block/textured.obj",
    "brick": "061_foam_brick/textured.obj",
    "bowl": "024_bowl/textured.obj",
    "cracker box": "003_cracker_box/cracker_box.stl",
    "cereal box": "003_cracker_box/cracker_box.stl",
    "large box": "003_cracker_box/cracker_box.stl",
    "small can": "005_tomato_soup_can/tomato_soup_can.stl",
    "can": "005_tomato_soup_can/tomato_soup_can.stl",
    "sugar box": "004_sugar_box/sugar_box.stl",
    "mustard bottle": "006_mustard_bottle/mustard_bottle.stl",
    "tuna fish can": "007_tuna_fish_can/textured.obj",
    "pudding box": "008_pudding_box/pudding_box.stl",
    "gelatin box": "009_gelatin_box/gelatin_box.stl",
    "potted meat can": "010_potted_meat_can/potted_meat_can.stl",
    "banana": "011_banana/banana.stl",
    "bleach cleanser": "021_bleach_cleanser/textured.obj",
}

IDX_TO_YCB_MESH = {
    1: "002_master_chef_can/master_chef_can.stl",
    2: "003_cracker_box/cracker_box.stl",
    3: "004_sugar_box/sugar_box.stl",
    4: "005_tomato_soup_can/tomato_soup_can.stl",
    5: "006_mustard_bottle/mustard_bottle.stl",
    6: "007_tuna_fish_can/textured.obj",
    7: "008_pudding_box/pudding_box.stl",
    8: "009_gelatin_box/gelatin_box.stl",
    9: "010_potted_meat_can/potted_meat_can.stl",
    10: "011_banana/banana.stl",
    11: "019_pitcher_base/textured.obj",
    12: "021_bleach_cleanser/textured.obj",
    13: "024_bowl/textured.obj",
    14: "025_mug/mug.stl",
    15: "035_power_drill/textured.obj",
    16: "036_wood_block/textured.obj",
    17: "037_scissors/textured.obj",
    18: "040_large_marker/textured.obj",
    20: "052_extra_large_clamp/textured.obj",
    21: "061_foam_brick/textured.obj",
}

NAME_TO_YCB_MESH = {
    "can": "002_master_chef_can/master_chef_can.stl",
    "box": "003_cracker_box/cracker_box.stl",
    "sugar box": "004_sugar_box/sugar_box.stl",
    "soup can": "005_tomato_soup_can/tomato_soup_can.stl",
    "bottle": "006_mustard_bottle/mustard_bottle.stl",
    "tuna can": "007_tuna_fish_can/textured.obj",
    "pudding box": "008_pudding_box/pudding_box.stl",
    "gelatin box": "009_gelatin_box/gelatin_box.stl",
    "meat can": "010_potted_meat_can/potted_meat_can.stl",
    "banana": "011_banana/banana.stl",
    "pitcher": "019_pitcher_base/textured.obj",
    "cleanser": "021_bleach_cleanser/textured.obj",
    "bowl": "024_bowl/textured.obj",
    "mug": "025_mug/mug.stl",
    "drill": "035_power_drill/textured.obj",
    "block": "036_wood_block/textured.obj",
    "scissors": "037_scissors/textured.obj",
    "marker": "040_large_marker/textured.obj",
    "clamp": "052_extra_large_clamp/textured.obj",
    "brick": "061_foam_brick/textured.obj",
}

IDX_TO_YCB_NAME = {
    1: "can",
    2: "box",
    3: "sugar box",
    4: "soup can",
    5: "bottle",
    6: "tuna can",
    7: "pudding box",
    8: "gelatin box",
    9: "meat can",
    10: "banana",
    11: "pitcher",
    12: "cleanser",
    13: "bowl",
    14: "mug",
    15: "drill",
    16: "block",
    17: "scissors",
    18: "marker",
    20: "clamp",
    21: "brick",
}

OBJECT_ORIGINAL2NEW_DICT = {
    "cylinderlarge": "large cylinder",
    "mug": "mug",
    "elephant": "elephant",
    "hand": "hand",
    "cubelarge": "large cube",
    "stanfordbunny": "stanfordbunny",
    "airplane": "airplane",
    "alarmclock": "alarmclock",
    "alarm clock": "alarmclock",
    "banana": "banana",
    "body": "body",
    "bowl": "bowl",
    "cubesmall": "small cube",
    "cup": "cup",
    "doorknob": "doorknob",
    "cubemedium": "medium cube",
    "eyeglasses": "eyeglasses",
    "flashlight": "flashlight",
    "flute": "flute",
    "gamecontroller": "gamecontroller",
    "hammer": "hammer",
    "headphones": "headphones",
    "knife": "knife",
    "lightbulb": "lightbulb",
    "mouse": "mouse",
    "phone": "phone",
    "piggybank": "piggybank",
    "pyramidlarge": "large pyramid",
    "pyramidsmall": "small pyramid",
    "pyramidmedium": "medium pyramid",
    "duck": "duck",
    "scissors": "scissors",
    "spherelarge": "large sphere",
    "spheresmall": "small sphere",
    "stamp": "stamp",
    "stapler": "stapler",
    "table": "table",
    "teapot": "teapot",
    "toruslarge": "large torus",
    "torussmall": "small torus",
    "train": "train",
    "watch": "watch",
    "cylindersmall": "small cylinder",
    "waterbottle": "waterbottle",
    "torusmedium": "medium torus",
    "cylindermedium": "medium cylinder",
    "spheremedium": "medium sphere",
    "wristwatch": "wristwatch",
    "wineglass": "wineglass",
    "camera": "camera",
    "binoculars": "binoculars",
    "fryingpan": "fryingpan",
    "toothpaste": "toothpaste",
    "apple": "apple",
    "toothbrush": "toothbrush",
}

OBJECT_NEW2ORIGINAL_DICT = {
    "large cylinder": "cylinderlarge",
    "mug": "mug",
    "elephant": "elephant",
    "hand": "hand",
    "large cube": "cubelarge",
    "stanfordbunny": "stanfordbunny",
    "airplane": "airplane",
    "alarmclock": "alarmclock",
    "alarm clock": "alarmclock",
    "banana": "banana",
    "body": "body",
    "bowl": "bowl",
    "small cube": "cubesmall",
    "cup": "cup",
    "doorknob": "doorknob",
    "medium cube": "cubemedium",
    "eyeglasses": "eyeglasses",
    "flashlight": "flashlight",
    "flute": "flute",
    "gamecontroller": "gamecontroller",
    "hammer": "hammer",
    "headphones": "headphones",
    "knife": "knife",
    "lightbulb": "lightbulb",
    "mouse": "mouse",
    "phone": "phone",
    "piggybank": "piggybank",
    "large pyramid": "pyramidlarge",
    "small pyramid": "pyramidsmall",
    "medium pyramid": "pyramidmedium",
    "duck": "duck",
    "scissors": "scissors",
    "large sphere": "spherelarge",
    "small sphere": "spheresmall",
    "stamp": "stamp",
    "stapler": "stapler",
    "table": "table",
    "teapot": "teapot",
    "large torus": "toruslarge",
    "small torus": "torussmall",
    "train": "train",
    "watch": "watch",
    "small cylinder": "cylindersmall",
    "waterbottle": "waterbottle",
    "medium torus": "torusmedium",
    "medium cylinder": "cylindermedium",
    "medium sphere": "spheremedium",
    "wristwatch": "wristwatch",
    "wineglass": "wineglass",
    "camera": "camera",
    "binoculars": "binoculars",
    "fryingpan": "fryingpan",
    "toothpaste": "toothpaste",
    "apple": "apple",
    "toothbrush": "toothbrush",
}
